### PR TITLE
Set up JEST and Webpack

### PR DESCRIPTION
**Pull request by joel-kalema**
- [x] Set up JEST.
- [x] Set up Webpack.

### CODE REVIEW

**Review by tylher — CHANGES_REQUESTED** [review]
Great job with the jest installation 🏆 but one more addition before moving on : 
You could install Babel for the project so es6 syntax can be used to import and export modules during testing, what do you think?

You can find how to install babel [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/testing/lesson_more_about_unit_tests_in_js.md)

Cheers! and happy coding.

**Comment by joel-kalema** [comment]
- [ ] Thank you for your feedback, let me install it.

**Review by tylher — APPROVED** [review]
## Status: Approve ✔️ 
Nothing more to say than time to merge. Great job!!!
the-wolf-of-wall-street-clap
Thank you for making the changes.

Cheers and happy coding!

**Comment by joel-kalema** [comment]
Thank you

**Pull request merged**
